#CC=g++
#CFLAGS=-O3 -Wall -shared -fpic -std=c++11
#LDFLAGS=
# Hardcoded -o !!
#SOURCES=main.cpp -o AStar.cpp
#OBJECTS=$(SOURCES:.cpp=.so)
all:
	g++ main.cpp AStar.cpp -o main.so -O3 -Wall -shared -fpic -std=c++11
#	g++ main.cpp -o main.o -O3 -Wall -shared -fpic -std=c++11
#	g++ -shared -o main.so main.o
#	$(CC) $(SOURCES) -o $(OBJECTS) $(CFLAGS) $(LDFLAGS)
