// Generated by gencpp from file robot_ai_scheduler/AIGenericCommandResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_AI_SCHEDULER_MESSAGE_AIGENERICCOMMANDRESPONSE_H
#define ROBOT_AI_SCHEDULER_MESSAGE_AIGENERICCOMMANDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_ai_scheduler
{
template <class ContainerAllocator>
struct AIGenericCommandResponse_
{
  typedef AIGenericCommandResponse_<ContainerAllocator> Type;

  AIGenericCommandResponse_()
    : response_code(0)
    , reason()  {
    }
  AIGenericCommandResponse_(const ContainerAllocator& _alloc)
    : response_code(0)
    , reason(_alloc)  {
  (void)_alloc;
    }



   typedef int16_t _response_code_type;
  _response_code_type response_code;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _reason_type;
  _reason_type reason;




  typedef boost::shared_ptr< ::robot_ai_scheduler::AIGenericCommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_ai_scheduler::AIGenericCommandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AIGenericCommandResponse_

typedef ::robot_ai_scheduler::AIGenericCommandResponse_<std::allocator<void> > AIGenericCommandResponse;

typedef boost::shared_ptr< ::robot_ai_scheduler::AIGenericCommandResponse > AIGenericCommandResponsePtr;
typedef boost::shared_ptr< ::robot_ai_scheduler::AIGenericCommandResponse const> AIGenericCommandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_ai_scheduler::AIGenericCommandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_ai_scheduler::AIGenericCommandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_ai_scheduler

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robot_ai_scheduler': ['/home/jack/Programming/Robotics/RobotOS/src/robot_ai_scheduler/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_ai_scheduler::AIGenericCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_ai_scheduler::AIGenericCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_ai_scheduler::AIGenericCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_ai_scheduler::AIGenericCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_ai_scheduler::AIGenericCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_ai_scheduler::AIGenericCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_ai_scheduler::AIGenericCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a40e2e8a729fb2f435e3fce71dfeed71";
  }

  static const char* value(const ::robot_ai_scheduler::AIGenericCommandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa40e2e8a729fb2f4ULL;
  static const uint64_t static_value2 = 0x35e3fce71dfeed71ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_ai_scheduler::AIGenericCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_ai_scheduler/AIGenericCommandResponse";
  }

  static const char* value(const ::robot_ai_scheduler::AIGenericCommandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_ai_scheduler::AIGenericCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 response_code\n\
string reason\n\
\n\
";
  }

  static const char* value(const ::robot_ai_scheduler::AIGenericCommandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_ai_scheduler::AIGenericCommandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response_code);
      stream.next(m.reason);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AIGenericCommandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_ai_scheduler::AIGenericCommandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_ai_scheduler::AIGenericCommandResponse_<ContainerAllocator>& v)
  {
    s << indent << "response_code: ";
    Printer<int16_t>::stream(s, indent + "  ", v.response_code);
    s << indent << "reason: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.reason);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_AI_SCHEDULER_MESSAGE_AIGENERICCOMMANDRESPONSE_H
