// Generated by gencpp from file robot_mapping_pathfinder/GetPathWaypoints.msg
// DO NOT EDIT!


#ifndef ROBOT_MAPPING_PATHFINDER_MESSAGE_GETPATHWAYPOINTS_H
#define ROBOT_MAPPING_PATHFINDER_MESSAGE_GETPATHWAYPOINTS_H

#include <ros/service_traits.h>


#include <robot_mapping_pathfinder/GetPathWaypointsRequest.h>
#include <robot_mapping_pathfinder/GetPathWaypointsResponse.h>


namespace robot_mapping_pathfinder
{

struct GetPathWaypoints
{

typedef GetPathWaypointsRequest Request;
typedef GetPathWaypointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPathWaypoints
} // namespace robot_mapping_pathfinder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_mapping_pathfinder::GetPathWaypoints > {
  static const char* value()
  {
    return "faeb4d9752daba214ce90de021e3676d";
  }

  static const char* value(const ::robot_mapping_pathfinder::GetPathWaypoints&) { return value(); }
};

template<>
struct DataType< ::robot_mapping_pathfinder::GetPathWaypoints > {
  static const char* value()
  {
    return "robot_mapping_pathfinder/GetPathWaypoints";
  }

  static const char* value(const ::robot_mapping_pathfinder::GetPathWaypoints&) { return value(); }
};


// service_traits::MD5Sum< ::robot_mapping_pathfinder::GetPathWaypointsRequest> should match 
// service_traits::MD5Sum< ::robot_mapping_pathfinder::GetPathWaypoints > 
template<>
struct MD5Sum< ::robot_mapping_pathfinder::GetPathWaypointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_mapping_pathfinder::GetPathWaypoints >::value();
  }
  static const char* value(const ::robot_mapping_pathfinder::GetPathWaypointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_mapping_pathfinder::GetPathWaypointsRequest> should match 
// service_traits::DataType< ::robot_mapping_pathfinder::GetPathWaypoints > 
template<>
struct DataType< ::robot_mapping_pathfinder::GetPathWaypointsRequest>
{
  static const char* value()
  {
    return DataType< ::robot_mapping_pathfinder::GetPathWaypoints >::value();
  }
  static const char* value(const ::robot_mapping_pathfinder::GetPathWaypointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_mapping_pathfinder::GetPathWaypointsResponse> should match 
// service_traits::MD5Sum< ::robot_mapping_pathfinder::GetPathWaypoints > 
template<>
struct MD5Sum< ::robot_mapping_pathfinder::GetPathWaypointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_mapping_pathfinder::GetPathWaypoints >::value();
  }
  static const char* value(const ::robot_mapping_pathfinder::GetPathWaypointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_mapping_pathfinder::GetPathWaypointsResponse> should match 
// service_traits::DataType< ::robot_mapping_pathfinder::GetPathWaypoints > 
template<>
struct DataType< ::robot_mapping_pathfinder::GetPathWaypointsResponse>
{
  static const char* value()
  {
    return DataType< ::robot_mapping_pathfinder::GetPathWaypoints >::value();
  }
  static const char* value(const ::robot_mapping_pathfinder::GetPathWaypointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MAPPING_PATHFINDER_MESSAGE_GETPATHWAYPOINTS_H
