// Generated by gencpp from file robot_mapping_pathfinder/MappingPathfinderGetPathServiceResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_MAPPING_PATHFINDER_MESSAGE_MAPPINGPATHFINDERGETPATHSERVICERESPONSE_H
#define ROBOT_MAPPING_PATHFINDER_MESSAGE_MAPPINGPATHFINDERGETPATHSERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace robot_mapping_pathfinder
{
template <class ContainerAllocator>
struct MappingPathfinderGetPathServiceResponse_
{
  typedef MappingPathfinderGetPathServiceResponse_<ContainerAllocator> Type;

  MappingPathfinderGetPathServiceResponse_()
    : waypoints()  {
    }
  MappingPathfinderGetPathServiceResponse_(const ContainerAllocator& _alloc)
    : waypoints(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose2D_<ContainerAllocator> >::other >  _waypoints_type;
  _waypoints_type waypoints;




  typedef boost::shared_ptr< ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MappingPathfinderGetPathServiceResponse_

typedef ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceResponse_<std::allocator<void> > MappingPathfinderGetPathServiceResponse;

typedef boost::shared_ptr< ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceResponse > MappingPathfinderGetPathServiceResponsePtr;
typedef boost::shared_ptr< ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceResponse const> MappingPathfinderGetPathServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_mapping_pathfinder

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b9e83915d91f5a57f9839688cdeccfb";
  }

  static const char* value(const ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b9e83915d91f5a5ULL;
  static const uint64_t static_value2 = 0x7f9839688cdeccfbULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_mapping_pathfinder/MappingPathfinderGetPathServiceResponse";
  }

  static const char* value(const ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose2D[] waypoints\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MappingPathfinderGetPathServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "waypoints[]" << std::endl;
    for (size_t i = 0; i < v.waypoints.size(); ++i)
    {
      s << indent << "  waypoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.waypoints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MAPPING_PATHFINDER_MESSAGE_MAPPINGPATHFINDERGETPATHSERVICERESPONSE_H
