// Generated by gencpp from file robot_mapping_pathfinder/MappingPathfinderGetPathService.msg
// DO NOT EDIT!


#ifndef ROBOT_MAPPING_PATHFINDER_MESSAGE_MAPPINGPATHFINDERGETPATHSERVICE_H
#define ROBOT_MAPPING_PATHFINDER_MESSAGE_MAPPINGPATHFINDERGETPATHSERVICE_H

#include <ros/service_traits.h>


#include <robot_mapping_pathfinder/MappingPathfinderGetPathServiceRequest.h>
#include <robot_mapping_pathfinder/MappingPathfinderGetPathServiceResponse.h>


namespace robot_mapping_pathfinder
{

struct MappingPathfinderGetPathService
{

typedef MappingPathfinderGetPathServiceRequest Request;
typedef MappingPathfinderGetPathServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MappingPathfinderGetPathService
} // namespace robot_mapping_pathfinder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_mapping_pathfinder::MappingPathfinderGetPathService > {
  static const char* value()
  {
    return "faeb4d9752daba214ce90de021e3676d";
  }

  static const char* value(const ::robot_mapping_pathfinder::MappingPathfinderGetPathService&) { return value(); }
};

template<>
struct DataType< ::robot_mapping_pathfinder::MappingPathfinderGetPathService > {
  static const char* value()
  {
    return "robot_mapping_pathfinder/MappingPathfinderGetPathService";
  }

  static const char* value(const ::robot_mapping_pathfinder::MappingPathfinderGetPathService&) { return value(); }
};


// service_traits::MD5Sum< ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceRequest> should match 
// service_traits::MD5Sum< ::robot_mapping_pathfinder::MappingPathfinderGetPathService > 
template<>
struct MD5Sum< ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_mapping_pathfinder::MappingPathfinderGetPathService >::value();
  }
  static const char* value(const ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceRequest> should match 
// service_traits::DataType< ::robot_mapping_pathfinder::MappingPathfinderGetPathService > 
template<>
struct DataType< ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceRequest>
{
  static const char* value()
  {
    return DataType< ::robot_mapping_pathfinder::MappingPathfinderGetPathService >::value();
  }
  static const char* value(const ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceResponse> should match 
// service_traits::MD5Sum< ::robot_mapping_pathfinder::MappingPathfinderGetPathService > 
template<>
struct MD5Sum< ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_mapping_pathfinder::MappingPathfinderGetPathService >::value();
  }
  static const char* value(const ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceResponse> should match 
// service_traits::DataType< ::robot_mapping_pathfinder::MappingPathfinderGetPathService > 
template<>
struct DataType< ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceResponse>
{
  static const char* value()
  {
    return DataType< ::robot_mapping_pathfinder::MappingPathfinderGetPathService >::value();
  }
  static const char* value(const ::robot_mapping_pathfinder::MappingPathfinderGetPathServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MAPPING_PATHFINDER_MESSAGE_MAPPINGPATHFINDERGETPATHSERVICE_H
