(cl:defpackage robot_ai_scheduler-srv
  (:use )
  (:export
   "AIGENERICCOMMAND"
   "<AIGENERICCOMMAND-REQUEST>"
   "AIGENERICCOMMAND-REQUEST"
   "<AIGENERICCOMMAND-RESPONSE>"
   "AIGENERICCOMMAND-RESPONSE"
   "TIMERCOMMAND"
   "<TIMERCOMMAND-REQUEST>"
   "TIMERCOMMAND-REQUEST"
   "<TIMERCOMMAND-RESPONSE>"
   "TIMERCOMMAND-RESPONSE"
   "TIMERGETTIME"
   "<TIMERGETTIME-REQUEST>"
   "TIMERGETTIME-REQUEST"
   "<TIMERGETTIME-RESPONSE>"
   "TIMERGETTIME-RESPONSE"
  ))

