(cl:defpackage robot_mapping_pathfinder-srv
  (:use )
  (:export
   "GETPATHWAYPOINTS"
   "<GETPATHWAYPOINTS-REQUEST>"
   "GETPATHWAYPOINTS-REQUEST"
   "<GETPATHWAYPOINTS-RESPONSE>"
   "GETPATHWAYPOINTS-RESPONSE"
  ))

